### ISSUE TITLE
Hi harsh! I didn't see any dicom files

### ISSUE THREAD

**Issue by scott-zz-li** [harsh1795/Intern-GE-HealthCare#1]
Thanks for your sharing! I want to try this program, but I didn't see any .dicom file, Would you like to send me the DICOM file that on the Readme page?

**Comment by harsh1795** [comment]
Hi benzxa, I am glad you found this useful. Actually, data used for this project is private and cannot be shared. If you wan't to try some open-source data. You can go for Kaggle competition Data Science Bowl.

Thanks,
Harshit
